### ISSUE TITLE
Better handling for boolean values

### ISSUE THREAD

**Issue by chippyash** [spatie/array-to-xml#122]
When parsing boolean values, the parser outputs `<ele>1</ele>` for a true value else `<ele></ele>` for false. As this is likely to break XML validation dependent on schema being employed, it would be better to allow specific handling of bools. Legal values for boolean are true, false, 1 (which indicates true), and 0 (which indicates false).

example:
```
features:
  feature1:
    enabled: true
    title: 'The module title'
  feature2:
    enabled: false
    tags: ~
  feature3:
    enabled: true
    variant: 2
```
will output:
```
<features>
    <feature1>
        <enabled>1</enabled>
        <title>The module title</title>
    </feature1>
    <feature2>
        <enabled></enabled>
        <tags></tags>
    </feature2>
    <feature3>
        <enabled>1</enabled>
        <variant>2</variant>
    </feature3>
</features>
```
The Yaml was parsed using the Symfony/Yaml parser.  That is correctly setting the enabled items in the resultant PHP array to either true or false.

Can we have an option to specify bool handling in the parser?
